version: '3.8'
services:
  postgres:
    image: postgres
    container_name: go-homework-5
    ports:
      - "6666:5432"
    environment:
      POSTGRES_DB: homework-5
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
